### ISSUE TITLE
종합 과제

### ISSUE THREAD

**Issue by simeddk** [simeddk/Tore07_GAS#1]
### 1. 프로젝타일 관련 코스매틱
- 프로젝타일 날아가는 소리 : AudioComp 활용해 볼 것(사운드큐와 사운드감쇠도 적용)
- 임팩트 소리 : PlaySoundAtLocation 활용해 볼 것(이왕이면 랜덤 사운드로)
![image](https://github.com/user-attachments/assets/4581d75e-2ee8-4a3c-94d8-e63c43b59c32)
- 임팩트 시 카메라쉐이크 주기(이번에는 UGameplayStatics::PlayWorldCameraShake 함수 써보기)
- 이미 카메라쉐이크 클래스 에셋은 컨텐츠 브라우저 안에 있습니다!(따로 만들 필요 없고, 가져다 쓰시면 됩니다.)
![image](https://github.com/user-attachments/assets/d75ad55d-5494-4870-9c52-9e35ae343725)

### 2. 플레이어 피격
- 플레이어 피격되었을 때 TargetDummy와 동일하게 Impact 머티리얼 적용하기
- 단, 색상 변경을 할 수 있도록 파마미터 추가할 것(빨갛게 빛나게 한다던지..)
![image](https://github.com/user-attachments/assets/459d8773-1e0e-48f5-837b-8dec7d85c344)

### 3. MaxHealth 개념 적용할 것
- 적절한 클래스 안에서 MaxHealth라는 신규 변수를 추가할 것
- 체력 계산하는 곳을 찾아서 Clamp를 줄 것(0 ~ MaxHealth)
- WB_PlayerHealth에서 `클래스 디폴트값`을 사용하는 곳을 찾아서 정당한 노드로 수정할 것

### 4. (보너스 과제) 포션 시스템
- 상자, 레버 스위치처럼 F 눌러서 상호작용 반응하면 됨
- 대미지를 입은 상태에서만 먹을 수 있도록
![image](https://github.com/user-attachments/assets/0525677d-cb45-43b3-a194-3dfb32e258e7)
- 한번 섭취한 포션은 10초동안 사라졌다가 다시 나타나도록(비활성화 -> 일정 시간 후 재활성화)
![image](https://github.com/user-attachments/assets/d508e61c-e6ef-43fe-a72b-bdd18a257155)
- 단, 체력이 꽉 찬 상태에서는 아무런 상호작용이 되면 안됨(먹어져서도 안되며, 사라져서도 안됨)

**Comment by jslee629** [comment]
이진성

https://youtu.be/mB6eJna-cdY

**Comment by HyeonLang** [comment]
김재우
https://youtu.be/jREItdD7QBg

**Comment by yongstar98** [comment]
김용호
https://youtu.be/wSwahjkCtDI

**Comment by hyeseo-dev** [comment]
남궁혜서

https://youtu.be/lROz0dMQySQ

**Comment by Ren-ame** [comment]
김기범
https://cafe.naver.com/sgagamedev/36628?boardType=L
