### ISSUE TITLE
액션 과제

### ISSUE THREAD

**Issue by simeddk** [simeddk/Tore07_GAS#2]
1. 분노 게이지
-> 내가 맞을 때
-> 블랙홀 사용하려면 분노 게이지 소비
-> 프로그레스바 위젯

2. 가시 반격
-> 피해는 받되, 대미지를 일부(10%, 20% 정도)
-> 소수는 올림
-> 패시브 스킬
-> UCAction::StartAction 에서 AttributeComp::OnHealthChaged에 가시반격 바인딩
-> RemoveDynamic을 적절한 위치에서 사용하기

3. 보너스 과제
 >1 적이 플레이어를 발견하면 ! 위젯으로 띄우기
 >2-1 플레이어의 워프는 기본 스킬에서 삭제
 >2-2 상호작용이 가능한 송아지를 상호작용했을 때, 워프 습득

**Comment by jslee629** [comment]
이진성

YouTube: https://www.youtube.com/watch?v=5S2Cx2qP1Es
repository: https://github.com/jslee629/U07_GAS/tree/Assignment1

**Comment by HyeonLang** [comment]
김재우
https://youtu.be/GlbJMn1oH0g
https://github.com/HyeonLang/U07_GAS/tree/0901_HW

**Comment by hiki25** [comment]
정의철 
YouTube : https://youtu.be/fwmCj-rSrL4
GitHub : https://github.com/hiki25/U07_GAS/tree/Assinmanet/Source/GAS
